### PR TITLE
Add instruction in README.

### PR DESCRIPTION
**Pull request by Yashwants19**

### CODE REVIEW

**Review by rcurtin — COMMENTED** [review]
Do you think it's sufficient to link to the website documentation instead?  I worry that this will slowly become out of date if we forget to update it or maintain it.  My guess is that this `mlpack-go` repository will be mostly forgotten about since it is just for distribution. :)

**Comment by Yashwants19** [comment]
Should I remove this completely, or filter this with only the installation part. As this `README` will also reflect [here](https://pkg.go.dev/mlpack.org/v1/mlpack?tab=overview).

**Comment by Yashwants19** [comment]
One more thing, we should also add LICENSE in this repository.

**Comment by rcurtin** [comment]
Hmm, personally I think that maybe it's best if we just link to the Go quickstart guide, and keep these build instructions there.  That way any updates are in the main repository.  Does that sound okay to you?

**Comment by rcurtin** [comment]
License added in 01dc1233f. :+1:

**Comment by Yashwants19** [comment]
> Hmm, personally I think that maybe it's best if we just link to the Go quickstart guide, and keep these build instructions there. That way any updates are in the main repository. Does that sound okay to you?

This sounds reasonable. :) I can close this PR.

Thank You

**Pull request closed without merging**
